---
version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - TRANSMISSION_WEB_HOME= #optional
      - USER=-e FILE__TRANSMISSION_USERNAME=/run/secrets/mysecretnames
      - PASS=-e FILE__TRANSMISSION_PASS=/run/secrets/mysecretnames
      - WHITELIST= #optional
      - PEERPORT=51413
      - HOST_WHITELIST= #optional
    volumes:
      - /media/t_conf:/config
      - /media/downloads:/downloads
      - /media/t_watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
